"""create_product_customization_and_related_tables

Revision ID: 326f6c1597a9
Revises: 6cc4cccfb8d6
Create Date: 2023-03-24 14:09:15.252938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326f6c1597a9'
down_revision = '6cc4cccfb8d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheese_amts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cheese_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crust_thicknesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crust_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sauce_amts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sauce_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_customizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('crust_type_id', sa.Integer(), nullable=False),
    sa.Column('crust_thickness_id', sa.Integer(), nullable=False),
    sa.Column('cheese_type_id', sa.Integer(), nullable=False),
    sa.Column('cheese_amt_id', sa.Integer(), nullable=False),
    sa.Column('sauce_type_id', sa.Integer(), nullable=False),
    sa.Column('sauce_amt_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cheese_amt_id'], ['cheese_amts.id'], ),
    sa.ForeignKeyConstraint(['cheese_type_id'], ['cheese_types.id'], ),
    sa.ForeignKeyConstraint(['crust_thickness_id'], ['crust_thicknesses.id'], ),
    sa.ForeignKeyConstraint(['crust_type_id'], ['crust_types.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sauce_amt_id'], ['sauce_amts.id'], ),
    sa.ForeignKeyConstraint(['sauce_type_id'], ['sauce_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_customization_toppings',
    sa.Column('product_customization_id', sa.Integer(), nullable=False),
    sa.Column('topping_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_customization_id'], ['product_customizations.id'], ),
    sa.ForeignKeyConstraint(['topping_id'], ['toppings.id'], ),
    sa.PrimaryKeyConstraint('product_customization_id', 'topping_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_customization_toppings')
    op.drop_table('product_customizations')
    op.drop_table('sauce_types')
    op.drop_table('sauce_amts')
    op.drop_table('crust_types')
    op.drop_table('crust_thicknesses')
    op.drop_table('cheese_types')
    op.drop_table('cheese_amts')
    # ### end Alembic commands ###
