"""relationship_cart_item_product_cust

Revision ID: cdf274203c08
Revises: f6959475f990
Create Date: 2023-04-07 13:04:47.587960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf274203c08'
down_revision = 'f6959475f990'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_items_cart_id_fkey', 'cart_items', type_='foreignkey')
    op.drop_constraint('cart_items_product_customization_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cart_items', 'product_customization_id')
    op.drop_constraint('carts_user_id_fkey', 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('product_customizations', sa.Column('cart_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product_customizations', 'cart_items', ['cart_item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_customizations', type_='foreignkey')
    op.drop_column('product_customizations', 'cart_item_id')
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key('carts_user_id_fkey', 'carts', 'users', ['user_id'], ['id'])
    op.add_column('cart_items', sa.Column('product_customization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_product_customization_id_fkey', 'cart_items', 'product_customizations', ['product_customization_id'], ['id'])
    op.create_foreign_key('cart_items_cart_id_fkey', 'cart_items', 'carts', ['cart_id'], ['id'])
    # ### end Alembic commands ###
