"""add_cart_tables_update_topping_association_table

Revision ID: f6959475f990
Revises: 4a1a3a079515
Create Date: 2023-04-01 11:38:29.206646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6959475f990'
down_revision = '4a1a3a079515'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anon_token', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_customization_id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_customization_id'], ['product_customizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product_customization_toppings', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('product_customization_toppings', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('product_customization_toppings_product_customization_id_fkey', 'product_customization_toppings', type_='foreignkey')
    op.create_foreign_key(None, 'product_customization_toppings', 'product_customizations', ['product_customization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_customization_toppings', type_='foreignkey')
    op.create_foreign_key('product_customization_toppings_product_customization_id_fkey', 'product_customization_toppings', 'product_customizations', ['product_customization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('product_customization_toppings', 'updated_at')
    op.drop_column('product_customization_toppings', 'created_at')
    op.drop_table('cart_items')
    op.drop_table('carts')
    # ### end Alembic commands ###
